version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install in build phase..."
  build:
    commands:
      - echo "Zipping application files for CodeDeploy..."
artifacts:
  files:
    - '**/*'
